### ISSUE TITLE
Button not showing when replying to individual tweets

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Tweeeeeeeeeeeeeeeeeeter#2]
Thanks to @3941 for finding this - https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/issues/1#issuecomment-245459204

**Comment by Noitidart** [comment]
Hey @3941 please try out this  - superb find! I am actually not a Twitter user so I would never have discovered this!

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/460709/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by 3941** [comment]
Yup, working now. Good work :+1:

**Comment by Noitidart** [comment]
Awesome! While I slept i thought of some ideas for a nicer editor I'm going to try that before the release. I'll keep you posted.

**Comment by Noitidart** [comment]
Wow man the work from today was pretty cool. Check it out:

After installing please go to `chrome://tweeeeeeeeeeeeeeeeeeter/content/resources/pages/editor.html` and you can see the new editor. I haven't yet added a emotication thing yet. I need some stock images for that maybe. I think I'll put it next to the "Image" icon.

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/462926/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by 3941** [comment]
That's a lot more than I asked for 😂
Which isn't bad. It's cool if you can get a little creative, because in the end you're just rendering to an image, so there is no conflict with Twitter capabilities.

**Comment by Noitidart** [comment]
I work for people that appreciate my work man! This ones all driven by you! :)

**Comment by 3941** [comment]
Yeah this has clearly given you quite a boost. You make me feel responsible kinda 😅

About the emojis, I'm not really sure how it works. The smilies, and symbols and all, are all defined by Unicode. However, different platforms seem to render them differently. On Firefox, I think that's mostly defined by font size.

The add-on I'm using for Twitter is EmojiT. Maybe you can get some... inspiration from it... 😉

**Comment by Noitidart** [comment]
Hahaha man you not only appreciate the work but you tried to get my addon more publicity and did research on that. This is the least I can do! :)

I'll check out that addon :)

**Comment by 3941** [comment]
A little screenshot from the new editor:
http://i.imgur.com/hhlYN3v.png

They don't really match the Twitter style though, which would be a plus.
I think you should try to make the default style as close to a normal, focussed on (zoomed in?), tweet as possible. That goes for everything, font style and size too.

**Comment by Noitidart** [comment]
Holy heck that is sweeeeeet!

Thanks for the find on that no line break thing! I'll see what I can do about that.

**Comment by Noitidart** [comment]
Yes! The hard part was done. I connected the editor to the tweet, try it out from Twitter! I need to now make the background transparent and touch up the editor for font colors and more fonts, localization etc.
Getting close to releasing this! :)
[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/464225/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by 3941** [comment]
Put it to the test and ran into a problem when trying to change font colour.
Not a priority but I thought I'd try the formatting options.

Ended up with an empty little box I could neither press ok nor cancel in and had to reload twitter in another tab.

Hmmm, and now the editor doesn't even want to open anymore. I guess it still thinks it's openend, because I've never properly closed it.

**Comment by Noitidart** [comment]
Thanks man for that test. Yep I'm working on the color stuff now, its a tricky one.
