### ISSUE TITLE
Emoji Codes and Descriptions

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/Tweeeeeeeeeeeeeeeeeeter#3]
Hey @3941 can you please help me find a list of all the emoji codes and their descriptions. I got this so far:

http://www.fileformat.info/info/unicode/block/emoticons/list.htm

**Comment by Noitidart** [comment]
I'm trying to make a dropdown with a filter box where you can type. And also on mouse over it will show a tooltip of what the emoji is doing. This is the startings of it:

![](http://i.imgur.com/ZqDcVaq.png)

**Comment by 3941** [comment]
http://unicode.org/emoji/charts/full-emoji-list.html
This is a complete list. There's a column for Twitter and apparently it supports them all. That's a shitload...

**Comment by Noitidart** [comment]
Oh wow superb! Thank you!!!

**Comment by 3941** [comment]
Btw, when I put emojis in your editor, it seems to use the "Windows" variant of them. I don't know if there's any way to make it use the Twitter variant, but that would of course be pretty cool.

**Comment by Noitidart** [comment]
Oh yikes, didn't notice that. It's because I'm not injecting into the twitter website. I'll have to work on that.  Ideally I wanted to inject the form onto the website, but their styles and scripts were fighting my editor so hard. It was overkill for me to fight it back.

**Comment by Noitidart** [comment]
Alrighty man here is the color menus done. The last thing before release is the emoji menu and hopefuly twitter style emotes. Please test this version out to see if its ok. Its localized and everything. Just emoji left.
[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465017/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by Noitidart** [comment]
@3941 i can't help but think about this while I sleep! I found the solution! Since I'm turning them to image anyways, it doesn't matter if it's unicode, so I'm going to let them choose what style they want. And it will just have image. So you can use apple style on windows. Or whatever! Sooo stoked man I loved collaborating with you!

Will do this when I wake up in the morning! :) Gotta write a harvester to harvest it from that site.

**Comment by 3941** [comment]
Just tried the latest version, tried all the formatting options (I think) and couldn't get it to fail.
Line break seems to not work when some formatting is going on though.

And of course you'd have to set a good default size. I don't know what you had before, but that worked fine. The new canvas is a little small.

About the emojis, I'm not sure if you can just set it to whatever you want. I think the code is the same for all, but the environment governs the style. I'm guessing Twitter maybe has some javascript on their site that points to their own graphics,

**Comment by 3941** [comment]
Hm, maybe this is helpful:
https://blog.twitter.com/2014/open-sourcing-twitter-emoji-for-everyone
https://github.com/twitter/twemoji

**Comment by Noitidart** [comment]
@3941 thanks for those links they were nice I tried it, I think i have to try it some more because with the current approach the smilies are not respecting font size - they have to currently be sized individually as they are images. Try it out:

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465454/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by Noitidart** [comment]
Oh I just saw your edit to the review:

> EDIT: After a very fruitful dialogue with the developer, I'm making this a 5 star review pre-emptively.

Thank you very much! AMO is silly and doesn't inform when reviews are edited. :(

**Comment by 3941** [comment]
Tried it. Yeah, that's kinda suboptimal with the smilies :)

**Comment by Noitidart** [comment]
How about for a next version release we'll go with this and I'll research more on those emojis? Is the amount of emojis ok or do you think the full selection is needed? I limited it to the first 77 for now.

**Comment by Noitidart** [comment]
Hey @3941 Im now using high quality SVGs so they can scale to whatever size. And on insert it detects the current font size and sizes it like that. Check it out!

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465526/Tweeeeeeeeeeeeeeeeeeter.zip)

![](http://i.imgur.com/lcfBGSt.png)

**Comment by 3941** [comment]
That seems to work pretty well. For whatever reason though, this happens now?
![shot](http://i.imgur.com/PezPSyM.png)

**Comment by Noitidart** [comment]
Oh yeah. The svgs are named like: `1f1f6.svg` but on the full list the code is `U+1F1F6` so my conversion code is failing. For example I have to figure out what to convert `U+1F912` to get the face with thermomenter - ![](http://i.imgur.com/bLvuLDK.png)

If you can help me figure that out just by finding the face with thermometer in the svg folder that would help me immensely! Im digging through it right now but can't find it.

Folder is here `jar:file:///C:/Users/Mercurius/AppData/Roaming/Mozilla/Firefox/Profiles/cx4w5lvy.Nightly%20Tester/extensions/Tweeeeeeeeeeeeeeeeeeter@jetpack.xpi!/resources/images/3rd/twemoji-svg/`

**Comment by Noitidart** [comment]
I'm also working on pagination and filtering for that right now, so i can show more then just the first 77 :)

**Comment by 3941** [comment]
I'll dig through the folder, just need some tool to look at them. I'm not very well equipped for vector graphics right now. But don't worry, I'll find something.

**Comment by Noitidart** [comment]
Thanks so much I am horribly equipped for it too haha. I have no idea how to even start. Ill keep working on the pagination its coming out nice!

**Comment by 3941** [comment]
Alright, I found something that works really well. An extension for the Windows Explorer:
https://svgextension.codeplex.com/releases/view/118790
Be sure to download the correct architecture for your system.

Anyway, I went through it and I'm pretty sure the little thermometer guy just isn't in there.

**Comment by 3941** [comment]
I'm downloading the whole open source emoji twitter thing right now. I assume it has more files you can add, so your code should find all the ones that are missing. 

I'll make an archive of just the svg part once it's here. It's quite big.

**Comment by Noitidart** [comment]
Thanks man so much! I juuust finished the filter and pagination of the emojis! It came out super nice! Try it out! Use the up/down arrow keys to paginate :)

Would love your feedback on it from a usability point of view.

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465567/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by Noitidart** [comment]
Holy heck that svg viewer as catalog thing is perfect what we needed! What did you even search to find something like that!! Haha you are truly an amazing searcher haha!

**Comment by 3941** [comment]
I'm actually quite proud of my Google-Fu 😁

**Comment by 3941** [comment]
Pagination works, but I'd rather have a more standard control.
A scrollbar and mousewheel support would be most intuitive I guess.

Negative on the download I just made... Same set of smilies. Which is weird. I'll try their release downloads.
It's far too few. They say they support almost 2k

**Comment by Noitidart** [comment]
Let me try the scrollbar thing and get back to you.

Awesome idea on the release downloads. Hopefully they have it there.

**Comment by 3941** [comment]
Ahhhh, I found the missing files. I assume you downloaded the open source twitter emojis from github too, right? They're in the folder named "2" for version 2. There's another svg folder with 1,830 files.

**Comment by 3941** [comment]
Just in case you didn't. Here you go: http://drei941.tk/svg.zip

**Comment by Noitidart** [comment]
Holy heck!!! I spent so much time trying to find all of them when I first found the SVGs wowww thank you!!!!!

Inserting it now!

Update on the scrollbar issue. If I dont use scrollbar it freezes the GUI, in the version with the updated SVGs ill leave out the pagination to show you what i mean.

**Comment by Noitidart** [comment]
Man you collaborating with me feels sooo awesome. I so love team work contributions (like translations), you doing that is such a serioussss help! Thank youuu!!

**Comment by 3941** [comment]
I could help with German, should you need something localised.

**Comment by Noitidart** [comment]
Thanks! I'll add you to the german localization team when i get this onto Babelzilla, may you please sign up at http://beta.babelzilla.org/ - You can see how I work with translators here for instance - https://github.com/Noitidart/NativeShot/issues/46

Alright here is the version with all SVGs and using no pagination (just scrollbar) it has gui freeze. With pagination it has no freeze.

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465597/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by 3941** [comment]
I'm not even getting a scrollbar, just a veeeery long list of emojis.
I guess the "freeze" is Firefox rendering all those SVG's. 
Wouldn't it be more efficient to use the provided PNG's or better even, use Twitter's server?

They're hosted like this: `https://abs.twimg.com/emoji/v2/72x72/1f602.png`

**Comment by Noitidart** [comment]
AMO reviewers don't allow remote assets. :(

I'll try with PNGs now.

**Comment by 3941** [comment]
The add-on I'm using for emojis on Twitter is doing this: http://i.imgur.com/P61Brdc.png
Then it just takes emoji by emoji from that image and puts them in the list.
I assume that speeds up loading a lot.

At least, what you could do is use the 16x16 emojis for your list, so no scaling is happening.
The editor already takes time to load as it is. Maybe you should think about implementing some indicator that it started loading. You know, rotating dots or the like.

**Comment by 3941** [comment]
Signed up to Babelzilla btw. Same nick as I have here.

**Comment by Noitidart** [comment]
Dang pngs same issue.

Loading idea is good idea. I didn't accomdate for that yet because even if they hit it multiple times it will just open multiple editors and they'll just have to close it multiple times.

I think we're good for release for this version what do you think?

As we get more users we'll have more motivation to fine tune it, what do you think?

**Comment by Noitidart** [comment]
Even localization lets push that to next version. Its an effort to coordinate and stuff. I'll ping you when i upload this to babelzilla :)

**Comment by Noitidart** [comment]
Man that guys emoji list is ugly! Ours is so much more usable no? Can search :D We also have some nice margin around it lol

**Comment by 3941** [comment]
If you want to release it like this, at least do a little bit of polishing beforehand.
Make the default width 558 pixels. That's the width of pics on "zoomed in" tweets and shouldn't need any downsizing. It will downscale them for "default view" tweets.

And can we make the height dynamic? Before we just entered text and it would make a proper sized picture. Now it feels a bit like we're using a graphical editor. The options are great but first priority should be usability, and that means, open, type, press okay and be done. Writing tweets is fast, so it should be as simple as possible.

And, of course, also remove the "rawr" before you release 😂

**Comment by 3941** [comment]
Oh, that's not how the list looks.
Looks like this:
![](http://i.imgur.com/98AeXx2.png)

They all come from that single image though.

**Comment by Noitidart** [comment]
Oh dang that guys list is pretty nice. Haha

Shoot yeah i need to polish it haha I put in so much work im like shoot gotta get this out now lol

Forgot about the "rawr" 📦 
That 558 width is genius! I had no idea about that!

What about height?

**Comment by Noitidart** [comment]
Oh height dynamic. I'll work on that for next version please its not a quick thing :(

**Comment by 3941** [comment]
Hey I'm not forcing you to do anything. You're the one pressing for release.

I'm just saying, try to keep it usable, because ironically, you're actually moving back on usability, while adding a lot of complexity. Which is great, but now users have to set their own height for every tweet they write. The basic functionality should be kept as simple as possible.

**Comment by Noitidart** [comment]
Ah true :(

I added some tweaks for usability. Hiting Ctrl + Enter anytime will be like clicking the "Accept" button.

On load it starts with focus in the editable.

Ok I'll see what I can do about the height :)

**Comment by 3941** [comment]
Those are great changes. I'm actually used to that combo from various instant messaging services.

**Comment by Noitidart** [comment]
Holy heck you are quite the motivator! You should be a manager! Look what you made me do!!

The resize now tells you its Minimum Height :)

It was MUCH quicker then I thought!

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465626/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by 3941** [comment]
Yeah I'd take that. Vastly overpaid job and all I do is direct people around.
Preferably while sitting on my ass at home, and chugging beer like I'm doing now. 😂
Backseat programmer basically.

**Comment by Noitidart** [comment]
HAHAHAHA!!!! Managers ftw >_< lol

I have to give it icons for "Strike" "Underline" and "Smileys". Other then that do you think it's set for release?

**Comment by 3941** [comment]
Oh now you took that away from me... I just made this screenshot 😂
![](http://i.imgur.com/hhlYN3v.png)

No wait, that's wrong... uhhhh
I meant to post this one:
![](http://i.imgur.com/JHZxHjM.png)

**Comment by 3941** [comment]
And btw, I LOVE the emoji search, but could we get just one more way to go through the pages? Like mousewheel at least?

Using the cursor keys is just so interrupting when you're using a mouse for basically everything.

**Comment by Noitidart** [comment]
Woohoo haha i love the search too :D Ooo muosewheel is  brilliant! Will hook that up now!

**Comment by 3941** [comment]
Just came back from taking a huge dump and I came up with an alternative name.
I like the current one, because it's funny and kinda clever, but I think it might be counterproductive when it's about searching for add-ons and first impressions.

I've seen you've thanked somebody for the name, and I really don't wanna piss on their party, so feel free to reject my suggestion. You don't owe me anything, because you're already giving me this add-on and it doesn't matter to me how it's called.

Anyway...
InfiniTweet <- dammit, it's taken -.-

**Comment by 3941** [comment]
Fuck... Can I ever have a great idea that nobody had before?
http://www.infinitweet.com/ a fucking iOS app....
And it's on Chrome too! meh... https://chrome.google.com/webstore/detail/infinitweet-chrome/lfakienppjdijjlmedhiekfmlpkmdbjp?hl=en

**Comment by Noitidart** [comment]
HAHAHAHAHAHA!!!!! You are tooo funny!

I like your name, let's go ahead and change it to that. What do you think? They don't have a capital T. Also our addon is better then theirs huh? Theirs is just plain text right? Like my v1.0?

Here is it with the icons for strike,underline,list number, smiliey. Wheel support. And also now when you click a smilie you don't see any lag time between resize, it is inserted at that size.

[Tweeeeeeeeeeeeeeeeeeter.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465647/Tweeeeeeeeeeeeeeeeeeter.zip)

**Comment by 3941** [comment]
I dunno. It's a risk. It all looks pretty professional and they might sue you or something...
This is them: http://secondhalf.tech/

Moving on to try it now.

**Comment by Noitidart** [comment]
Aw shoot yeah screw that hahaha - I just added Infinitweet to the tags section :D 

Theirs is not even inlaid into Twitter like ours. So we have a one on them there already.

**Comment by 3941** [comment]
Oh that's a genius idea actually.

**Comment by 3941** [comment]
Back from testing. Looks really good!
I think it's in a releasable state.

For the future, overlay the screen to lock it and display loading animation when the button is pressed.
Or even better, reduce loading time somehow.
And it would be cool if we could see Twitter in the background, maybe through a toned, but transparent background.
Also, maybe split the toolbar into two rows. Would look better because the editing area is so narrow and it would also help with lower resolution screens.

But it's very usable right now, I think,

**Comment by Noitidart** [comment]
Woohoo. I ran the build script on it. This is the release version before release. It removes all the console logging and debug stuff. It should actually even open the frame faster.

I tried hard on that transparent thing but couldn't get it to work. I'll shoot for next version on that.

Please test this dist version, if its good for you I'll do the upload. Sometimes when remove all the dev stuff it breaks something.

You'll notice this version is much bigger in size because it has no compression. Firefox loads addons synchronously so the higher the compression the longer it takes firefox to startup. Thats why dist version is built with no compression.

[dist.zip](https://github.com/Noitidart/Tweeeeeeeeeeeeeeeeeeter/files/465651/dist.zip)

**Comment by 3941** [comment]
All looks really good, and works. I think you can release it like this.
I ran into another problem for the future though.
If the image ends up being higher than 560px, twitter will cut parts at the top and bottom, and you have to click it to see the whole thing.

So, I'm not really thinking about putting a limit in there, but maybe a warning that it will do that, once you reach something above 560 pixels.

This is how it looks then: (don't wonder about the image... I just needed something to paste there and had that website still open)
![](http://i.imgur.com/ppzUeY6.png)

**Comment by Noitidart** [comment]
HAHAHAHAHAHAAHAHAHAH I LOVE THAT TWEET! Mocking Infinitweet with the awesome features it lacks but Tweeeeter has :D :D 

Uploading now :)

**Comment by 3941** [comment]
I'll still try and think about another name btw...

I think it would be cool if you would have a little watermark at the bottom right of each image, but you need a simpler name for that. Nobody is going to count all the E's to put it into Google.

So all your users would also be advertising for you. I'm sure that would help a lot.

**Comment by Noitidart** [comment]
Totally agree. Maybe we should just rename it to "Tweeeeeter" for now. Just 3 additional e's?

I really hope this gets more popular then Infinitweet. Do tweeters find this thing useful? I know the image makes their tweets less searchable. That's why in description I recommend them to put the callouts and hashtags in the text part, and then the rest in this image.

**Comment by 3941** [comment]
If there strangely weren't so many results for that, I'd support it...
https://www.google.de/search?q=tweeeeeter&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=3YTUV8jBKq2P8QeXzoWIAw

It needs to be something more unique...

**Comment by Noitidart** [comment]
Holy heck that is so funny lol!

**Comment by Noitidart** [comment]
That line break issue was fixed on accident by the way. When I removed the fixed height, and used dynamic height it works even for the emoji's :)

I'll close this issue as its resolved :)

**Comment by Noitidart** [comment]
Hahaha while messing with the search filter I found something hilarious. They didn't want to be racist so they didn't use keywords "black" or "white" or "brown". If you want smilies of super white people you search "type-1" if you want tan white people you go "type-2" if you want black people you type "type-5" and if you want dark black you type "type-6" this is so funny!

**Comment by Noitidart** [comment]
I left a review EmojiT addon, I told him if his addon is Firefox only I'll help him land support for this search/sort/filter thing. :)

If it's not Firefox only I think I'll have to make a competing addon haha

**Comment by Noitidart** [comment]
Do you have any ideas on how to make this more popular? Like get it into the hands of more people? Do tweeters find this technology very useful?
I'm going to try to  talk to some people I know on the featuring addons team to see if they can somehow bump this or something even though I have few users.
